export const SOO_REGISTRY_VERSION = "v0.3.9.1 prototype" as const;
export const requirementStatuses = ["supported", "partially-supported", "planned", "data-dependent", "unsupported", "out-of-scope"] as const;
export type RequirementStatus = typeof requirementStatuses[number];
export const requirementDomains = ["planning-geography", "facility-identification", "facility-characteristics", "population-context", "demographic-vulnerability", "access", "resilience", "evidence-provenance", "scenario-analysis", "data-governance", "licensed-data-readiness", "safety-and-scope"] as const;
export type RequirementDomain = typeof requirementDomains[number];
export type SourceDependencyType = "public" | "licensed" | "derived" | "user-provided" | "unavailable" | "future";
export type CapabilityId = string;
export interface SourceDependency { sourceId: string; displayName: string; sourceType: SourceDependencyType; active: boolean; required: boolean; purpose: string; limitation?: string; }
export interface SooRequirement { id: `ST-SOO-${string}`; title: string; domain: RequirementDomain; secondaryDomains: RequirementDomain[]; objective: string; status: RequirementStatus; currentCapabilities: CapabilityId[]; sourceDependencies: SourceDependency[]; applicationSurfaces: ("workspace" | "evidence-brief" | "exports" | "data-sources")[]; evidenceFields: string[]; exportSurfaces: ("evidence-json" | "evidence-markdown" | "hospital-csv" | "county-demographic-csv" | "county-demographic-json" | "requirements-json")[]; testReferences: string[]; limitations: string[]; futureWork: string[]; safetyNotes: string[]; outOfScopeReason?: string; roadmap?: { targetVersion?: string; prerequisiteRequirementIds?: string[]; blockedByRequirementIds?: string[] }; lastReviewedVersion: typeof SOO_REGISTRY_VERSION; }
const activeCapabilities = new Set(["planning-location-search","planning-location-marker","planning-radius","county-boundary-context","cms-hospital-identification","facility-details","county-acs-context","national-acs-benchmark","straight-line-access","evidence-brief","structured-exports","source-provenance","missing-data-semantics","safety-guardrails","resilience-analysis","structured-planning-scenario"]);
export const capabilityRegistry = Object.fromEntries([...activeCapabilities].map(id => [id, { id, active: true }])) as Record<string, {id:string;active:boolean}>;
for (const id of ["radius-population-estimation","road-travel-time","rurality-analysis","facility-comparison","aha-attribute-ingestion","cms-aha-crosswalk","capacity-analysis"]) capabilityRegistry[id] = { id, active: false };
const publicSource = (sourceId:string, displayName:string, purpose:string): SourceDependency => ({sourceId, displayName, sourceType:"public", active:true, required:true, purpose});
const futureSource = (sourceId:string, displayName:string, purpose:string, sourceType:SourceDependencyType="future"): SourceDependency => ({sourceId, displayName, sourceType, active:false, required:true, purpose});
const r = (id: SooRequirement["id"], title:string, domain:RequirementDomain, status:RequirementStatus, capability:string[], source:SourceDependency[], limitations:string[], objective=`${title} for reproducible research and planning.`): SooRequirement => ({id,title,domain,secondaryDomains:[],objective,status,currentCapabilities:capability,sourceDependencies:source,applicationSurfaces:["workspace","evidence-brief"],evidenceFields:[],exportSurfaces:["evidence-json","requirements-json"],testReferences:status === "supported" ? ["soo-registry"] : [],limitations,futureWork:status === "supported" ? [] : ["Document and activate only with an appropriate validated method and source."],safetyNotes:[],lastReviewedVersion:SOO_REGISTRY_VERSION});
export const sooRequirements: SooRequirement[] = [
r("ST-SOO-001","Define a planning location","planning-geography","supported",["planning-location-search","planning-location-marker"],[publicSource("geocoding-proxy","Geocoding proxy","Resolve entered planning locations"),{sourceId:"user-provided-coordinates",displayName:"User-provided planning coordinates",sourceType:"user-provided",active:true,required:false,purpose:"Accept coordinates directly"}],["Geocoded positions may be approximate and are not validated incident locations."],"Allow the researcher to define a geographic point for analysis."),
r("ST-SOO-002","Define a straight-line planning radius","planning-geography","supported",["planning-radius"],[{sourceId:"derived-haversine",displayName:"Derived Haversine distance",sourceType:"derived",active:true,required:true,purpose:"Calculate 1–250 mile straight-line radius"}],["Not drive time, routing, terrain-aware, weather-aware, or aeromedical flight time."],"Allow a reproducible distance-based planning area."),
r("ST-SOO-003","Identify containing and intersecting counties","planning-geography","supported",["county-boundary-context"],[publicSource("tiger-county-boundaries","2024 TIGER/Line county boundaries","Associate county geography")],["County geography does not establish service responsibility or county-weighted population."]),
r("ST-SOO-004","Identify mapped hospitals within the planning radius","facility-identification","supported",["cms-hospital-identification","straight-line-access"],[publicSource("cms-hospitals","CMS public hospital records","Map hospital identity records")],["CMS records are not complete coverage, live operating status, or diversion status."],"Identify available mapped hospital records located within the selected straight-line radius."),
r("ST-SOO-005","Display facility identity and contact information","facility-identification","supported",["facility-details"],[publicSource("cms-hospitals","CMS public hospital records","Provide public identity and contact fields")],["Public contact information may be stale or unreported."],"Provide basic facility-identification fields for review."),
r("ST-SOO-006","Determine advanced facility capabilities","facility-characteristics","data-dependent",["aha-attribute-ingestion"],[futureSource("aha-facility-attributes","AHA facility attributes","Provide authorized validated facility characteristics","licensed")],["Capability must not be inferred from CMS identity records; missing data does not establish absence."],"Identify validated specialty, capacity, and operational facility characteristics."),
r("ST-SOO-007","Provide containing-county population context","population-context","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide 2020–2024 county estimates")],["Whole-county ACS context is not population inside the radius or current-year population."]),
r("ST-SOO-008","Estimate population inside the planning radius","population-context","planned",["radius-population-estimation"],[futureSource("acs-tract-boundaries","Future tract ACS and boundaries","Support documented spatial interpolation")],["Current county population must not be interpreted as radius population."]),
r("ST-SOO-009","Provide age-group context","demographic-vulnerability","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide age estimates")],["Age 18 to 64 is derived and lacks a separately supported count MOE."]),
r("ST-SOO-010","Provide poverty context","demographic-vulnerability","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide poverty universe context")],["Whole-county context is not causation or a patient-level measure."]),
r("ST-SOO-011","Provide health-insurance context","demographic-vulnerability","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide insurance context")],["Not hospital payer mix or current patient insurance status."]),
r("ST-SOO-012","Provide vehicle-access context","demographic-vulnerability","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide occupied household vehicle context")],["Not ambulance availability, road access, vehicle reliability, or travel time."]),
r("ST-SOO-013","Provide disability context","demographic-vulnerability","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide ACS disability context")],["Not clinical acuity, individual status, or accessibility certification."]),
r("ST-SOO-014","Provide limited-English-speaking household context","demographic-vulnerability","supported",["county-acs-context"],[publicSource("acs-county-2024","2024 ACS 5-year county data","Provide household language context")],["Not interpreter availability or individual language preference."]),
r("ST-SOO-015","Compare county values with United States benchmarks","demographic-vulnerability","supported",["national-acs-benchmark"],[publicSource("acs-us-2024","2024 ACS 5-year United States benchmark","Compare same-release metrics")],["Descriptive percentage-point comparison is not significance, causation, or a target."]),
r("ST-SOO-016","Measure straight-line facility access","access","supported",["straight-line-access"],[{sourceId:"derived-haversine",displayName:"Derived Haversine distance",sourceType:"derived",active:true,required:true,purpose:"Calculate proximity"}],["Not road distance, travel time, EMS response, transfer, or air transport time."]),
r("ST-SOO-017","Measure road travel time","access","planned",["road-travel-time"],[futureSource("routing-provider","Future routing provider","Calculate documented travel-time estimates")],["No current ETA or live routing."]),
r("ST-SOO-018","Evaluate rurality or geographic access burden","access","planned",["rurality-analysis"],[futureSource("rurality-classification","Future rurality classification","Assess geographic access burden")],["Current county and distance outputs are not a rurality score."]),
r("ST-SOO-019","Assess facility redundancy","resilience","partially-supported",["resilience-analysis","cms-hospital-identification"],[publicSource("cms-hospitals","CMS public hospital records","Count and locate mapped hospitals")],["Facility count alone is not a resilience score; capabilities, capacity, and constraints are missing."]),
r("ST-SOO-020","Assess facility capacity or surge capability","resilience","data-dependent",["capacity-analysis"],[futureSource("licensed-capacity-data","Future licensed or validated capacity data","Assess defined capacity","licensed")],["No beds, staffing, occupancy, or surge status; do not infer capacity from identity data."]),
r("ST-SOO-021","Assess real-time operational availability","safety-and-scope","out-of-scope",[],[futureSource("real-time-operational-data","Real-time operational data","Not used by this research platform")],["No live diversion, beds, staffing, dispatch, transfer acceptance, medical control, or air availability."]),
r("ST-SOO-022","Preserve source provenance","evidence-provenance","supported",["source-provenance","evidence-brief"],[publicSource("public-data-registry","Public-data source registry","Preserve releases, retrieval dates, and variables")],["Provenance reflects source data and methods at generation time."]),
r("ST-SOO-023","Preserve missing-data semantics","data-governance","supported",["missing-data-semantics"],[{sourceId:"derived-status-semantics",displayName:"Derived application status semantics",sourceType:"derived",active:true,required:true,purpose:"Preserve missing and unavailable values"}],["Missing, suppressed, unreported, invalid, or unavailable values are not zero or absence."]),
r("ST-SOO-024","Produce reproducible Evidence outputs","evidence-provenance","supported",["evidence-brief","structured-exports"],[{sourceId:"derived-evidence-outputs",displayName:"Derived Evidence outputs",sourceType:"derived",active:true,required:true,purpose:"Create reproducible exports"}],["Evidence is not a clinical report or operational directive."]),
r("ST-SOO-025","Define a structured planning scenario","scenario-analysis","supported",["structured-planning-scenario"],[{sourceId:"local-browser-storage",displayName:"Local browser storage",sourceType:"derived",active:true,required:true,purpose:"Persist one validated local planning scenario"}],["Planning scenarios are local research records, not clinical, dispatch, routing, transfer, or real-time operational guidance."]),
r("ST-SOO-026","Compare facilities within a scenario","scenario-analysis","planned",["facility-comparison"],[futureSource("normalized-facility-attributes","Future normalized attributes","Support documented comparison")],["No comparison or ranking without validated comparable attributes."]),
r("ST-SOO-027","Ingest licensed AHA facility attributes","licensed-data-readiness","data-dependent",["aha-attribute-ingestion"],[futureSource("aha-facility-attributes","AHA facility attributes","Future authorized licensed facility attributes","licensed")],["Inactive until authorization, governance, schema, access control, auditability, and export policy exist."]),
r("ST-SOO-028","Crosswalk CMS and AHA facility identities","licensed-data-readiness","planned",["cms-aha-crosswalk"],[futureSource("aha-facility-attributes","AHA facility attributes","Future CMS-to-AHA crosswalk","licensed")],["No crosswalk is implemented; unmatched and ambiguous records require explicit handling."]),
r("ST-SOO-029","Prevent clinical or operational interpretation","safety-and-scope","supported",["safety-guardrails"],[{sourceId:"derived-product-scope",displayName:"Derived product-scope guardrails",sourceType:"derived",active:true,required:true,purpose:"Exclude clinical and operational use"}],["No clinical advice, triage, dispatch, transfer recommendation, medical control, or patient-level inference."]),
r("ST-SOO-030","Prevent absence inference from missing data","safety-and-scope","supported",["missing-data-semantics","safety-guardrails"],[{sourceId:"derived-status-semantics",displayName:"Derived application status semantics",sourceType:"derived",active:true,required:true,purpose:"Prevent absence inference"}],["Missing or unreported information does not establish absence."])
];
sooRequirements.find(x=>x.id==="ST-SOO-021")!.outOfScopeReason = "StatTerrain is a research and planning platform, not a real-time operational system.";
sooRequirements.find(x=>x.id==="ST-SOO-025")!.applicationSurfaces=["workspace","evidence-brief","exports"]; sooRequirements.find(x=>x.id==="ST-SOO-025")!.evidenceFields=["planningScenario"]; sooRequirements.find(x=>x.id==="ST-SOO-025")!.exportSurfaces=["evidence-json","evidence-markdown","requirements-json"]; sooRequirements.find(x=>x.id==="ST-SOO-025")!.testReferences=["planning-scenario-schema","planning-scenario-validation","planning-scenario-evidence"]; sooRequirements.find(x=>x.id==="ST-SOO-025")!.roadmap={targetVersion:"v0.3.9.1"}; sooRequirements.find(x=>x.id==="ST-SOO-026")!.roadmap={targetVersion:"v0.3.9.2",blockedByRequirementIds:["ST-SOO-025"]}; sooRequirements.find(x=>x.id==="ST-SOO-027")!.roadmap={targetVersion:"v0.3.10"};
export function validateSooRequirements(requirements=sooRequirements): string[] { const ids=new Set<string>(); const errors:string[]=[]; for(const req of requirements){if(ids.has(req.id)||!/^ST-SOO-\d{3}$/.test(req.id)) errors.push(`invalid or duplicate ID: ${req.id}`); ids.add(req.id); if(!req.title.trim()||!req.objective.trim()) errors.push(`missing title/objective: ${req.id}`); if(!requirementStatuses.includes(req.status)||!requirementDomains.includes(req.domain)) errors.push(`invalid status/domain: ${req.id}`); if(req.status==="supported" && !req.currentCapabilities.some(id=>capabilityRegistry[id]?.active)) errors.push(`supported requirement lacks active capability: ${req.id}`); if(req.status==="data-dependent" && !req.sourceDependencies.some(s=>!s.active || s.sourceType==="licensed")) errors.push(`data-dependent requirement lacks inactive source: ${req.id}`); if(req.status==="out-of-scope"&&!req.outOfScopeReason) errors.push(`out-of-scope requirement lacks reason: ${req.id}`); if(req.lastReviewedVersion!==SOO_REGISTRY_VERSION) errors.push(`stale review version: ${req.id}`); for(const c of req.currentCapabilities) if(!capabilityRegistry[c]) errors.push(`unknown capability ${c}`); } return errors; }
export const requirementStatusLabel: Record<RequirementStatus,string>={supported:"Supported","partially-supported":"Partially supported",planned:"Planned","data-dependent":"Data dependent",unsupported:"Unsupported","out-of-scope":"Out of scope"};
export function getTraceabilitySummary(requirements=sooRequirements){const byStatus=Object.fromEntries(requirementStatuses.map(s=>[s,requirements.filter(r=>r.status===s).length])) as Record<RequirementStatus,number>; return {total:requirements.length,byStatus,byDomain:Object.fromEntries(requirementDomains.map(d=>[d,requirements.filter(r=>r.domain===d).length])),ahaDependent:requirements.filter(r=>r.sourceDependencies.some(s=>s.sourceId.includes("aha"))).map(r=>r.id),representedInEvidence:requirements.filter(r=>r.evidenceFields.length>0).map(r=>r.id),withExports:requirements.filter(r=>r.exportSurfaces.length>0).map(r=>r.id),lackingActiveSources:requirements.filter(r=>!r.sourceDependencies.some(s=>s.active)).map(r=>r.id)};}
export function selectRelevantRequirements(context:{hasHospitals?:boolean;hasCountyContext?:boolean;hasNationalBenchmark?:boolean;hasEvidence?:boolean;hasPlanningScenario?:boolean}={}) { const ids=["ST-SOO-001","ST-SOO-002","ST-SOO-022","ST-SOO-023","ST-SOO-029","ST-SOO-030"]; if(context.hasHospitals) ids.push("ST-SOO-004","ST-SOO-005","ST-SOO-016","ST-SOO-019","ST-SOO-006"); if(context.hasCountyContext) ids.push(...["ST-SOO-003","ST-SOO-007","ST-SOO-009","ST-SOO-010","ST-SOO-011","ST-SOO-012","ST-SOO-013","ST-SOO-014"]); if(context.hasNationalBenchmark) ids.push("ST-SOO-015"); if(context.hasEvidence) ids.push("ST-SOO-024"); if(context.hasPlanningScenario) ids.push("ST-SOO-025"); const relevantRequirementIds=[...new Set(ids)]; return {relevantRequirementIds,satisfiedRequirementIds:relevantRequirementIds.filter(id=>sooRequirements.find(r=>r.id===id)?.status==="supported"),partiallyRepresentedRequirementIds:relevantRequirementIds.filter(id=>sooRequirements.find(r=>r.id===id)?.status==="partially-supported"),unavailableRequirementIds:relevantRequirementIds.filter(id=>["planned","unsupported","out-of-scope"].includes(sooRequirements.find(r=>r.id===id)?.status??"")),futureDependencyIds:relevantRequirementIds.filter(id=>sooRequirements.find(r=>r.id===id)?.status==="data-dependent")}; }
