import { product } from "@/config/product";
import type { Facility } from "@/types/facility";

export const PLANNING_SCENARIO_SCHEMA_VERSION = "1.0" as const;
export const PLANNING_SCENARIO_STORAGE_KEY = "statterrain.activePlanningScenario.v1";
export const scenarioStatuses = ["draft", "ready-for-review", "archived"] as const;
export const researchFocusDomains = ["facility access", "hospital availability context", "population context", "demographic vulnerability", "geographic redundancy", "resilience planning", "data-gap review", "licensed-data readiness", "other"] as const;
export type PlanningScenarioStatus = typeof scenarioStatuses[number];
export interface PlanningScenario { schemaVersion: "1.0"; scenarioId:string; title:string; purpose:string; status:PlanningScenarioStatus; createdAt:string; updatedAt:string; createdWithVersion:string; lastUpdatedWithVersion:string; planningArea:{location:{label:string;latitude:number|null;longitude:number|null;source:"geocoded"|"coordinates"|"imported"|"unset"};radiusMiles:number|null;distanceMethod:"haversine-straight-line";containingCounty:{geoid:string|null;name:string|null;state:string|null;status:"available"|"unavailable"|"not-loaded"};intersectingCounties:{geoid:string|null;name:string|null;state:string|null}[]}; researchFocus:{domains:string[];customFocus:string}; selectedFacilities:ScenarioFacility[]; assumptions:ScenarioAssumption[]; researcherNotes:string; sourceState:Record<string,SourceState>; limitations:string[]; requirementsTraceability:{relevantRequirementIds:string[];futureDependencyIds:string[]}; provenance:Record<string,unknown>; }
export interface ScenarioAssumption {id:string;text:string;category:string;source:"user-entered"|"system-generated";createdAt:string;updatedAt:string}
export interface ScenarioFacility {facilityId:string;cmsCertificationNumber:string|null;name:string;facilityType:string|null;address:Record<string,string|null>;phone:string|null;latitude:number|null;longitude:number|null;distanceMiles:number|null;sourceClassification:string;selectionReason:string;selectedAt:string;snapshotStatus:"available"|"partial";currentAnalysisStatus:"in-current-results"|"outside-current-radius"|"unavailable-in-current-results"|"not-evaluated"}
export interface SourceState {status:"loaded"|"partial"|"unavailable"|"not-requested";recordCount:number|null;message:string|null;capturedAt:string|null;sourceId:string|null}
const defaults=["Facility distance is measured as straight-line distance from the planning location.","County demographic values describe the whole containing county, not the population inside the selected radius.","Missing or unreported information does not establish that a facility, capability, service, or population condition is absent.","Results reflect the source releases and retrieval dates recorded in the scenario provenance.","The scenario is for research and planning and does not provide clinical or real-time operational guidance."];
const limitations=["Stored locally unless exported.","Not a clinical record or real-time source.","Source values and facility records may become outdated or incomplete.","Missing information does not establish absence.","Straight-line distance is not travel time.","County context is not population within radius.","Imported snapshots are not automatically refreshed."];
const id=(prefix:string)=> { const uuid=globalThis.crypto?.randomUUID?.() ?? `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`; return `${prefix}_${uuid}`; };
const stamp=()=>new Date().toISOString();
export function createPlanningScenario():PlanningScenario { const now=stamp(); return {schemaVersion:PLANNING_SCENARIO_SCHEMA_VERSION,scenarioId:id("scenario"),title:"",purpose:"",status:"draft",createdAt:now,updatedAt:now,createdWithVersion:product.prototypeVersion,lastUpdatedWithVersion:product.prototypeVersion,planningArea:{location:{label:"",latitude:null,longitude:null,source:"unset"},radiusMiles:null,distanceMethod:"haversine-straight-line",containingCounty:{geoid:null,name:null,state:null,status:"not-loaded"},intersectingCounties:[]},researchFocus:{domains:[],customFocus:""},selectedFacilities:[],assumptions:defaults.map(text=>({id:id("assumption"),text,category:"research scope",source:"system-generated",createdAt:now,updatedAt:now})),researcherNotes:"",sourceState:{hospitals:{status:"not-requested",recordCount:null,message:null,capturedAt:null,sourceId:"cms-hospitals"},countyContext:{status:"not-requested",recordCount:null,message:null,capturedAt:null,sourceId:"acs-county-2024"},nationalBenchmarks:{status:"not-requested",recordCount:null,message:null,capturedAt:null,sourceId:"acs-us-2024"},countyBoundaries:{status:"not-requested",recordCount:null,message:null,capturedAt:null,sourceId:"tiger-county-boundaries"},geocoding:{status:"not-requested",recordCount:null,message:null,capturedAt:null,sourceId:"geocoding-proxy"}},limitations,requirementsTraceability:{relevantRequirementIds:["ST-SOO-001","ST-SOO-002","ST-SOO-022","ST-SOO-023","ST-SOO-024","ST-SOO-025","ST-SOO-029","ST-SOO-030"],futureDependencyIds:[]},provenance:{application:{version:product.prototypeVersion}}}; }
export function validatePlanningScenario(value:unknown):{valid:boolean;errors:string[];scenario?:PlanningScenario} { const s=value as PlanningScenario; const e:string[]=[]; if(!s||typeof s!=="object") e.push("Scenario must be an object."); if(s?.schemaVersion!=="1.0") e.push("This scenario uses an unsupported schema version."); if(!/^scenario_[A-Za-z0-9-]+$/.test(s?.scenarioId??"")) e.push("Scenario ID is invalid."); if(!scenarioStatuses.includes(s?.status)) e.push("Scenario status is invalid."); for(const [v,n] of [[s?.title,120],[s?.purpose,1000],[s?.researcherNotes,5000],[s?.researchFocus?.customFocus,250]] as const) if(typeof v!=="string"||v.length>n) e.push("A text field is invalid or too long."); const loc=s?.planningArea?.location; if(loc && ((loc.latitude!==null&&(!Number.isFinite(loc.latitude)||loc.latitude < -90||loc.latitude>90))||(loc.longitude!==null&&(!Number.isFinite(loc.longitude)||loc.longitude < -180||loc.longitude>180)))) e.push("Planning coordinates are invalid."); const r=s?.planningArea?.radiusMiles; if(r!==null&&(!Number.isFinite(r)||r<1||r>250)) e.push("Planning radius is invalid."); if(!Array.isArray(s?.assumptions)||s.assumptions.length>20||s.assumptions.some(a=>!a.text?.trim()||a.text.length>500))e.push("Assumptions are invalid."); if(!Array.isArray(s?.selectedFacilities)||s.selectedFacilities.length>250||s.selectedFacilities.some(f=>!f.facilityId||!f.name||f.selectionReason.length>500))e.push("Selected facilities are invalid."); if(!Array.isArray(s?.researchFocus?.domains)||s.researchFocus.domains.some(d=>!researchFocusDomains.includes(d as never)))e.push("Research focus is invalid."); return e.length?{valid:false,errors:e}:{valid:true,errors:[],scenario:s}; }
export function parsePlanningScenario(json:string){try{return validatePlanningScenario(JSON.parse(json));}catch{return {valid:false,errors:["The scenario file is not valid StatTerrain scenario JSON."]};}}
export function serializePlanningScenario(s:PlanningScenario){const result=validatePlanningScenario(s);if(!result.valid)throw new Error(result.errors.join(" "));return JSON.stringify(s,null,2);}
export function synchronizePlanningScenario(s:PlanningScenario, update:Partial<PlanningScenario["planningArea"]>):PlanningScenario{return {...s,planningArea:{...s.planningArea,...update,location:{...s.planningArea.location,...update.location},containingCounty:{...s.planningArea.containingCounty,...update.containingCounty}},updatedAt:stamp(),lastUpdatedWithVersion:product.prototypeVersion};}
export function facilitySnapshot(f:Facility):ScenarioFacility{return {facilityId:f.id,cmsCertificationNumber:f.sourceFacilityId??null,name:f.name,facilityType:f.facilityType??null,address:{line1:f.address??null,city:f.city??null,state:f.state??null,zip:f.zip??null},phone:f.phone??null,latitude:f.lat??null,longitude:f.lng??null,distanceMiles:f.distanceMiles??null,sourceClassification:f.isSynthetic?"synthetic-demo":"cms-public",selectionReason:"",selectedAt:stamp(),snapshotStatus:"available",currentAnalysisStatus:"in-current-results"};}
