import test from 'node:test';import assert from 'node:assert/strict';import { validateVariable, loadMetadata } from '../scripts/public-data/validate-acs-variable-metadata.mjs';import { ACS_COUNTY_METRICS } from '../scripts/public-data/acs-county-metric-registry.mjs';import { canCommitGeneratedArtifacts,evaluateNationalCompletion } from '../scripts/public-data/acs-workflow-gates.mjs';
const metric=ACS_COUNTY_METRICS[0]; const groups={B01003:{description:'Total Population'}}; const goodVars={B01003_001E:{label:'Estimate!!Total:',concept:'TOTAL POPULATION',predicateType:'int'},B01003_001M:{label:'Margin of Error!!Total:',concept:'TOTAL POPULATION',predicateType:'int'}};
test('concept text need not contain group ID and correct variable/group IDs pass',()=>{const r=validateVariable({metric,variableId:'B01003_001E',variables:goodVars,groups}); assert.equal(r.actualConcept.includes('B01003'),false); assert.equal(r.validationStatus,'PASS');});
test('wrong group ID fails',()=>{const r=validateVariable({metric,variableId:'B99999_001E',variables:{...goodVars,B99999_001E:goodVars.B01003_001E,B99999_001M:goodVars.B01003_001M},groups}); assert.equal(r.validationStatus,'FAIL'); assert.match(r.validationNotes.join(','),/wrong group ID/);});
test('missing variable fails',()=>{const r=validateVariable({metric,variableId:'B01003_999E',variables:goodVars,groups}); assert.equal(r.validationStatus,'FAIL'); assert.match(r.validationNotes.join(','),/missing required estimate variable/);});
test('E/M pair fails only when live validation fails, not when M metadata is absent',()=>{let r=validateVariable({metric,variableId:'B01003_001E',variables:{B01003_001E:goodVars.B01003_001E},groups}); assert.equal(r.validationStatus,'PASS'); r=validateVariable({metric,variableId:'B01003_001E',variables:{B01003_001E:goodVars.B01003_001E},groups,livePairStatus:'FAIL'}); assert.equal(r.validationStatus,'FAIL'); assert.match(r.validationNotes.join(','),/live query/);});
test('wrong semantic label fails',()=>{const r=validateVariable({metric,variableId:'B01003_001E',variables:{...goodVars,B01003_001E:{...goodVars.B01003_001E,label:'Estimate!!Cars'}},groups}); assert.equal(r.validationStatus,'FAIL'); assert.match(r.validationNotes.join(','),/label/);});
test('unsupported release fails',async()=>{await assert.rejects(()=>loadMetadata('2023',{fixture:true}),/Unsupported ACS release/);});
test('commit blocked when gates fail, run ID differs, any state fails, or validation fails',()=>{const status={runId:'1',buildMode:'national',metadataValidationStatus:'FAIL',probeStatus:'PASS',buildStatus:'PASS',artifactValidationStatus:'PASS'}; const manifest={runId:'2',countyRecordCount:4,partitions:{MI:{},OH:{},PR:{}},runSummary:{statesCompleted:['MI','OH','PR'],statesFailed:['OH'],duplicateGeoids:0,uniqueGeoids:4,expectedGeographyContractStatus:'PASS'}}; const r=canCommitGeneratedArtifacts(status,manifest,{commitRequested:true}); assert.equal(r.ok,false); assert.match(r.reasons.join(','),/metadata|runId|states failed|county count/);});
test('four fixture records cannot satisfy national completion guardrails',()=>{const s={runId:'x',buildMode:'national',metadataValidationStatus:'PASS',probeStatus:'PASS',buildStatus:'PASS',artifactValidationStatus:'PASS'}; const m={runId:'x',countyRecordCount:4,partitions:{MI:{},OH:{},PR:{}},runSummary:{statesCompleted:['MI','OH','PR'],statesFailed:[],duplicateGeoids:0,uniqueGeoids:4,expectedGeographyContractStatus:'PASS'}}; assert.equal(evaluateNationalCompletion(s,m).ok,false);});

test('requested release controls metadata URL and keyed URL is not reported',async()=>{await assert.rejects(()=>loadMetadata('2099',{fixture:false}),/Unsupported ACS release 2099/);});
