import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd();
const exp=readFileSync(join(root,'src/lib/export.ts'),'utf8');
test('versioned evidence schema records planning point and radius',()=>{assert.match(exp,/schemaVersion: "statterrain-evidence-v2"/);assert.match(exp,/planningLocation/);assert.match(exp,/radiusMiles: ctx\.radiusMiles/);assert.match(exp,/distanceMethod: "great-circle-haversine"/);});
test('schema includes source freshness methods limitations completeness',()=>{for (const word of ['sources:', 'humanReadable', 'methods:','limitations:','freshness:','completeness:']) assert.match(exp,new RegExp(word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('county ACS population is active while unsupported sections remain unavailable',()=>{assert.match(exp,/containingCounty: ctx\.containingCounty/);assert.match(exp,/intersectingCounties: ctx\.intersectingCounties/);assert.match(exp,/Whole-county ACS totals are not estimates/);assert.match(exp,/accessibility: null/);assert.match(exp,/resilience: null/);});
test('CMS evidence fields are retained',()=>{for (const word of ['cmsFacilityId','facilityName','county','coordinates','distanceFromPlanningLocationMiles','hospitalType','ownership','emergencyServices','criticalAccess','missingFieldStatus']) assert.match(exp,new RegExp(word));});
